const LOCALES = {
    LOG_IN_SUCCESS: 'LOG IN SUCCESS',
    CAN_NOT_LOG_IN: 'CAN NOT LOG IN',
    GET_LIST_USER_SUCCESS: 'GET LIST USER SUCCESS',
    CREATE_USER_SUCCESS: 'CREATE USER SUCCESS',
    CAN_NOT_CHANGE_PASSWORD: 'CAN NOT CHANGE PASSWORD',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE PASSWORD SUCCESS'
}

module.exports= {
    LOCALES
}